#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

user_resources="$XDG_CONFIG_HOME/X11/xresources"
[ -f "$user_resources" ] && xrdb -merge "$user_resources"

user_modmap="$XDG_CONFIG_HOME/X11/xmodmap"
[ -f "$user_modmap" ] && xmodmap "$user_modmap"

setxkbmap -option "caps:escape_shifted_capslock" &
redshift -PO 4000 &
slstatus &
dunst &

while true; do
    /usr/local/bin/dwm 2> /dev/null
done
